Organizations:

    - &LaSIGE

        Name: LaSIGE

        ID: LaSIGEMSP

        MSPDir: /bft-config/fabric/LaSIGE/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LaSIGEMSP.member')"

            Writers:
                Type: Signature
                Rule: "OR('LaSIGEMSP.member')"

            Admins:
                Type: Signature
                Rule: "OR('LaSIGEMSP.admin')"

        AnchorPeers:

            - Host: 0.peer.lasige.bft
              Port: 7051

    - &IBM

        Name: IBM

        ID: IBMMSP

        MSPDir: /bft-config/fabric/IBM/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('IBMMSP.member')"

            Writers:
                Type: Signature
                Rule: "OR('IBMMSP.member')"

            Admins:
                Type: Signature
                Rule: "OR('IBMMSP.admin')"

        AnchorPeers:

            - Host: 0.peer.ibm.bft
              Port: 7051

