NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.frontend.bft-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.frontend.bft-cert.pem
    OrganizationalUnitIdentifier: peer
